// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoklubBezbednost.Data;

#nullable disable

namespace MotoklubBezbednost.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430211907_AddRowVersionAndFkIndexes")]
    partial class AddRowVersionAndFkIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.CommentDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.EquipmentDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FormalShirt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Jacket")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pants")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Vest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WorkShirt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.LevelDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MemberDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmbg")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MemberTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegisteredOn")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Workplace")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Jmbg")
                        .IsUnique();

                    b.HasIndex("MemberTypeId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MemberTypeDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PaidMembership")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Prefix")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TypeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MemberTypes");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MembershipPaymentDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentForYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("MembershipPayments");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MotorcycleDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommercialName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EngineDisplacment")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterPlate")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Motorcycles");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.PaymentTypeDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.TagDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int?>("TagNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.TrainingDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCertificateIssued")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotorcycleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.TrainingSessionDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructors")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModificationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LevelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PolygonDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("TheoryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.CommentDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.MemberDb", null)
                        .WithMany("Comments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.EquipmentDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.MemberDb", null)
                        .WithOne("Equipment")
                        .HasForeignKey("MotoklubBezbednost.Data.Models.EquipmentDb", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MemberDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.MemberTypeDb", "MemberType")
                        .WithMany("Members")
                        .HasForeignKey("MemberTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MemberType");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MembershipPaymentDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.MemberDb", null)
                        .WithMany("MembershipPayments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoklubBezbednost.Data.Models.PaymentTypeDb", "PaymentType")
                        .WithMany("MembershipPayments")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MotorcycleDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.MemberDb", null)
                        .WithMany("Motorcycles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.TagDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.MemberDb", null)
                        .WithMany("Tags")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.TrainingDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.MemberDb", null)
                        .WithMany("Trainings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoklubBezbednost.Data.Models.MotorcycleDb", "Motorcycle")
                        .WithMany("Trainings")
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoklubBezbednost.Data.Models.TrainingSessionDb", "TrainingSession")
                        .WithMany("Trainings")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorcycle");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.TrainingSessionDb", b =>
                {
                    b.HasOne("MotoklubBezbednost.Data.Models.LevelDb", "Level")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Level");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.LevelDb", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MemberDb", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Equipment");

                    b.Navigation("MembershipPayments");

                    b.Navigation("Motorcycles");

                    b.Navigation("Tags");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MemberTypeDb", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.MotorcycleDb", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.PaymentTypeDb", b =>
                {
                    b.Navigation("MembershipPayments");
                });

            modelBuilder.Entity("MotoklubBezbednost.Data.Models.TrainingSessionDb", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
